In [15]:
import numpy as np
import cv2 
import matplotlib.pyplot as plt
import pandas as pd
from PIL import Image
import glob
import os
import re
import imutils
from skimage.feature import peak_local_max
from skimage.morphology import watershed
from scipy import ndimage
import collections
from skimage.draw import circle, line
from skimage.measure import regionprops
import tqdm
import matplotlib.image as mpimg
from scipy.spatial import distance as dist

In [16]:
def atoi(text):
   return int(text) if text.isdigit() else text
def natural_keys(text):
   return [atoi(c) for c in re.split('(\d+)', text)]

In [17]:
image_list = []
for filename in sorted(glob.glob('track_cells/*.tiff'), key=natural_keys): 
    im=cv2.imread(filename)
   
    image_list.append(im)

In [18]:
def return_cord(i_0):    
    cx = []
    cy = []

    shifted = cv2.pyrMeanShiftFiltering(i_0, 10, 51)
    gray = cv2.cvtColor(shifted,cv2.COLOR_BGR2GRAY)
    thresh = cv2.threshold(gray, 20, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)[1]
    D = ndimage.distance_transform_edt(thresh)
    localMax = peak_local_max(D, indices=False, min_distance=9, labels=thresh)
    markers = ndimage.label(localMax, structure=np.ones((3, 3)))[0]
    labels = watershed(-D, markers, mask=thresh)



    for label in np.unique(labels):
        if label == 0:
            continue




        mask = np.zeros(gray.shape, dtype='uint8')
        mask[labels == label] = 255
        cnts = cv2.findContours(mask.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        cnts = imutils.grab_contours(cnts)
        c = max(cnts, key=cv2.contourArea)
        ((x, y), r) = cv2.minEnclosingCircle(c)



        cx.append(int(x))
        cy.append(int(y))
        
        l1 = np.column_stack((cx,cy))
        

    return l1, cx, cy

In [19]:
def eucl_dist_matrix(cor_t, cor_t1):
    
    d = dist.cdist(cor_t, cor_t1)
    rows = d.min(axis=1).argsort()
    cols = d.argmin(axis=1)[rows]
    
    list_id_index = (list(zip(rows, cols)))
    list_id_index = sorted(list_id_index)
    
    
    
    
    return rows, cols, list_id_index ,d

In [20]:
def find_duplicates_col(rows, columns,list_id_index, distance_matrix):
    
    col = columns.tolist()
    duplicates = []
    for item in col:
        if col.count(item) > 1:
            duplicates.append(item)
    duplicate_columns = set(duplicates)
    
    d = []
    r = []
    c = []
    for ix, (a, b) in enumerate(zip(rows, columns)):
        for i in duplicate_columns: 
            if b == i:
                d.append(distance_matrix[a][b])
                r. append(a)
                c.append(b)
                
    w = (list(zip(r,c,d)))
    w.sort(key = lambda t: t[1])
    w
    
    temp = {}
    for row, col, di in w:
        if col not in temp: # we see this key for the first time
            temp[col] = (row, col, di)
        else:
            if temp[col][2] > di: # the new date is larger than the old one
                temp[col] = (row, col, di)

    result = temp.values()

    result = list(result)

    l2set = set(result)
    colums_to_remove = [x for x in w if x not in l2set] # cordinates that have to be removed
     
    rem_row, rem_col, rem_dit = zip(*colums_to_remove)
    rem_cor = (list(zip(rem_row,rem_col)))
    
    rem_cor = set(rem_cor)
    
    keep_cor = [x for x in list_id_index if x not in rem_cor]

    keep_cor.sort(key = lambda t: t[1])
    
    new_row, new_col = zip(*keep_cor)

    
    return new_row, new_col, duplicate_columns

In [21]:
def remove_duplicates(x, y, index):
    
    large = max(index)
    lst = list(range(0,(large+1)))
    
    ix = set(index)
    
    missing_ix = [x for x in lst if x not in ix]
    
    centroid_t = (list(zip(x,y)))
    
    real_centroid = [i for j, i in enumerate(centroid_t) if j not in missing_ix]
    
    x_i, y_i = zip(*real_centroid)
    
    stacket_centroids = np.column_stack((x_i,y_i))
    
    
    
    return(x_i, y_i, stacket_centroids)

In [22]:
i_1 = image_list[0]

i_2 = image_list[1]

i_3 = image_list[2]

In [23]:
cor_1,x1,y1 = return_cord(i_1)
cor_2,x2,y2 = return_cord(i_2)
cor_3,x3,y3 = return_cord(i_3)

In [24]:
rows_1_2, cols_1_2, list_id_index_1_2 ,d_1_2 = eucl_dist_matrix(cor_1, cor_2)

In [25]:
id_cell, index, duplicate_columns = find_duplicates_col(rows_1_2, cols_1_2, list_id_index_1_2, d_1_2)

In [26]:
x_2, y_2, new_cor_2 = remove_duplicates(x2,y2, id_cell)

In [27]:
df2 = pd.DataFrame(list(zip(x_2, y_2,id_cell)), 
               columns =['row', 'col', 'id_cell']) 


x = []
y = []
corrdinate = []
for i in range(len(df2)):
    x.append(df2.iloc[i,0])
    y.append(df2.iloc[i,1])
    corrdinate.append(df2.iloc[i,2])

    
    
for idx, i in enumerate(x):
    

    
    cv2.circle(i_2, (x[idx], y[idx]), 3, (0, 255, 255), -1)
    cv2.putText(i_2, "{0}".format(corrdinate[idx]), (x[idx] - 20, y[idx] - 20),
		cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 1)
    
cv2.imwrite('img_2.png', i_2)

True

In [28]:
df2

    row  col  id_cell
0   983   26        3
1    64   27        1
2   995   27        2
3   731   34        4
4   106   54        6
5   521   52        9
6   564   50        7
7   977   64        8
8   416   81       11
9   203   87       12
10  144  104       14
11  627  104       15
12  489  108       17
13  103  118       16
14   32  124       18
15  594  131       19
16  715  138       20
17  816  137       21
18  480  160       24
19   94  165       25
20  445  170       26
21   25  179       29
22  182  188       27
23  901  193       28
24  749  191       33
25  715  205       32
26  815  209       34
27  118  208       31
28  385  211       38
29   64  229       30
..  ...  ...      ...
54  346  682       65
55  440  688       66
56  585  704       67
57  247  714       68
58  944  721       69
59  533  728       70
60  982  738       71
61  215  741       72
62  418  751       74
63  313  802       76
64  384  809       77
65  656  830       78
66   52  842       79
67  223  850       80
68  150  855       81
69   76  874       82
70  933  876       83
71  553  873       84
72  721  888       85
73  668  906       87
74  331  905       88
75  766  919       89
76   35  920       90
77  721  944       91
78  776  944       93
79  987  973       92
80  331  980       94
81  146  985       95
82  573  994       96
83  687  999       97

[84 rows x 3 columns]

In [29]:
df = pd.DataFrame(list(zip(x1, y1)), 
               columns =['row', 'col']) 


x = []
y = []

for i in range(len(df)):
    x.append(df.iloc[i,0])
    y.append(df.iloc[i,1])
    #corrdinate.append(df2.iloc[i,2])

    
    
for idx, i in enumerate(x):
    

    
    cv2.circle(i_1, (x[idx], y[idx]), 3, (0, 255, 255), -1)
    cv2.putText(i_1, "{0}".format(idx), (x[idx] - 20, y[idx] - 20),
		cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 1)
    
cv2.imwrite('img_1.png', i_1)

True